apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance
        image: attendance-app:latest
        imagePullPolicy: Never