---
- name: Deploy Attendance App using Docker
  hosts: localhost
  become: yes

  tasks:
    - name: Run Docker container safely
      shell: |
        docker rm -f attendance-app || true
        docker run -d -p 5000:5000 --name attendance-app attendance-app